### ISSUE TITLE
SQL ISSUE

### ISSUE THREAD

**Issue by ghaffar47** [putera/jtkpk#1]
fail to create user table on "php artisan db:seed"

[Illuminate\Database\QueryException]                                         
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: ''   
  for column 'gred' at row 1 (SQL: insert into `users` (`name`, `email`, `pas  
  sword`, `remember_token`, `role`, `gred`, `kod_jpn`, `kod_ppd`, `kod_jabata  
  n`, `created_at`, `updated_at`) values (Pentadbir Sistem, admin@domain.com,  
   $2y$10$VzArNThE8p3lScLDKdjfj.C0cemY9IJmmYgXUgP8TTdUseMqR.lry, , super-admi  
  n, , , , , NOW(), NOW()))

**Comment by putera** [comment]
Try run composer update dulu then baru migrate data

**Comment by putera** [comment]
Telah dikemaskini dengan UsersDataSeeder.php yang baru. Boleh dapatkan kembali fail tersebut dan run

`$ php artisan db:seed --class=UsersDataSeeder`
