### ISSUE TITLE
migrate error

### ISSUE THREAD

**Issue by ghaffar47** [putera/jtkpk#2]
[Illuminate\Database\QueryException]                                         
  SQLSTATE[HY000]: General error: 1005 Can't create table `jtkpk`.`#sql-592_a  
  f` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter   
  table `user_roles` add constraint `user_roles_user_id_foreign` foreign key   
  (`user_id`) references `users` (`id`) on delete cascade)  

and 

                                                                              
  [PDOException]                                                               
  SQLSTATE[HY000]: General error: 1005 Can't create table `jtkpk`.`#sql-592_a  
  f` (errno: 150 "Foreign key constraint is incorrectly formed")

**Comment by putera** [comment]
Pull balik data dari repo..
```
git pull origin master
```
pastu

```
php artisan migrate:refresh
```

**Comment by ghaffar47** [comment]
done, tapi kene drop semua database lama
